### ISSUE TITLE
Fix group/role filtering from IDP

### ISSUE THREAD

**Issue by chrismccracken** [dotCMS/plugin-com.dotcms.dotsaml#39]
Needs to allow all, enable/disable sync (re: LDAP auth.impl.build.groups=true). Also needs to accommodate static assignment.

Config prop `build.roles` (string, not mandatory, silent default "all"):
- "all": Remove user from all roles, add to roles from IdP & `saml_user_role` (if set)
- "idp": Remove user from all roles, add to roles from IdP 
- "staticonly": Remove user from all roles, add to roles from `saml_user_role` (if set). Ignore roles from IdP.
- "staticadd": Do not alter existing user roles, add to roles from `saml_user_role` (if set). Ignore roles from IdP.
- "none": Do not alter user roles in any way

Make sure that `include.roles.pattern` & `remove.roles.prefix` work as intended, including when unset or empty (should match all and remove no prefix). Defaults for those options should be empty string.

**Comment by gabbydotCMS** [comment]
I think the default behavior is actually not altering roles in any way ("none" instad of "all").

This is what I did:

1. I logged into the backend with a brand new user (gabriela@dotcms.com). The account got created, and the only role assigned to the user was "SAML User"
2. I logged out.
3. Logged in as admin@dotcms.com, I assigned the role "System -> CMS Administrartor" to the new account.
4. I logged out.
5. I logged in as gabriela@dotcms.com, the role "System -> CMS Administrator" was not removed even when it's not been set by the IdP.

If the default behavior is "all", the user gabriela@dotcms.com should have gotten the role "System -> CMS Administrator" removed.

Gabby

**Comment by gabbydotCMS** [comment]
It'd be nice to throw a warning when build.roles=staticonly and saml_user_role (soon to be role.extra) is missing.

**Comment by gabbydotCMS** [comment]
It'd be nice to log a warning when build.roles has been assigned with an invalid value (anything different from "all", "idp", "staticonly", "staticadd", "none")

https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/3.0-4.2.x/src/com/dotcms/plugin/saml/v3/OpenSamlAuthenticationServiceImpl.java#L488-L491

**Comment by gabbydotCMS** [comment]
We need to make sure our clients are aware that when build.roles=staticadd and the value for saml_user_role gets changed, the old role will stay assigned to the users who already have it, for we don't remove roles at each login attempt on that mode.
Whenever the client needs to change the value of the saml_user_role in this mode, they will need to manually handle the old role that has already been assigned to users in the system.

**Comment by jdotcms** [comment]
DONE
