### ISSUE TITLE
Change property name from saml_user_role to role.extra

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#59]
Our saml_user_role property should be renamed as role.extra .

This is the property that allows the client to set a fixed role to be added to the users at each login attempt. It has noting to do with the role "SAML User" that we have to identify the users who have logged in via SAML.

https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/199e1cfd884b806d9ffe3a9f7bcf7a3f39f7e0e7/src/com/dotcms/plugin/saml/v3/DotSamlConstants.java#L397

**Comment by jdotcms** [comment]
Done!
