### ISSUE TITLE
Typo on "sevice.provider.custom.metadata.path"

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#65]
https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/199e1cfd884b806d9ffe3a9f7bcf7a3f39f7e0e7/src/com/dotcms/plugin/saml/v3/DotSamlConstants.java#L318-L319

We need to change sevice.provider.custom.metadata.path to be service.provider.custom.metadata.path

**Comment by jdotcms** [comment]
PR: https://github.com/dotCMS/plugin-com.dotcms.dotsaml/pull/66/files
