### ISSUE TITLE
REQ#1 - Create portlet's main view

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#69]
https://cocoaowl.mybalsamiq.com/projects/dotcmssamlportlet/Main%20SAML%20Config

For now use the DOJO Widget Set to build the UI.

**Comment by gabbydotCMS** [comment]
@oarrietadotcms I created the place holder HTML for the main view of the portlet.

This is what you need to work on:

1. Search. List should show results that match the config name, the  SP Issuer URL, the SP Endpoint Hostname, or any optional parameter.
2. Add new and edit. Both will use the view to be created on #70 .
3. Delete.
4. Set as default.

No need to work now on SP metadata download for now.

Let me know if you have any questions.

**Comment by jdotcms** [comment]
Awesome, it looks very cool.
Quick question: where is gonna be stored the configuration?

**Comment by gabbydotCMS** [comment]
@jdotcms JSON files under assets see: #72, #73, #74, and #75
