### ISSUE TITLE
REQ#1 - Switch to new configuration

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#78]
Version 3.0 of the plugin reads SAML configuration properties from two fields associated to the "Host" (site) content type.

Version 4.0 of the plugin moves all configuration properties to files stored in the asset folder.

The filter that controls the authentication process and any other elements associated to the SAML request processig need to be adapted so that all configuration parameters are taken from the JSON, private key, public certificate, and IdP Metada files managed through the new SAML Configuration portlet. Configuration info stored in files must be cached.

Requests to $Site/[login urls] (for example: https://demo.dotcms.com/dotAdmin/#/public/login) must be properly looked up from cache/JSON for  Site->SAML Config mapping and redirected to proper SAML Config’s IdP respectively.

**Comment by Nathan-Ethode** [comment]
@gabbydotCMS @oarrietadotcms 

I need to decipher which of these are from the main config and which are from the optionalProperties config.

Specifically on the main config there is a setting where they choose response, assertion, or both.

So I need to answer these three questions:

boolean isVerifyAssertionSignatureNeeded()

boolean isVerifySignatureProfileNeeded()

boolean isVerifySignatureCredentialsNeeded()

The first I'm assuming comes from the main config, but I'm not sure about the others? Could you clarify if these relate to the main assertion settings? For now I have assumed the other two are optionalProperties.

I left the original comments in place in case it helps.

![screen shot 2018-04-01 at 3 16 37 am](https://user-images.githubusercontent.com/37702082/38223678-129c9c16-36ba-11e8-8fd8-4350d5096bd4.png)

There is a special "signatureValidationType" property now. In the new spec it must be either "response", "assertion", or "responseandassertion". The user must choose one of those three options. I am wondering if/how these selections fit into those methods. I marked this with a blue arrow on new config JSON. Any property not specified is then optional and placed in the "optionalProperties" array, marked with the green arrow on the new config JSON.

So I'm asking if the new "signatureValidationType" property is related to any of those three boolean checks? If not, where would it be applied?

If all three are optional properties still that's fine and easy to check with the defined keys, but I'm looking to identify where the new "signatureValidationType" property fits in. "isVerifyAssertionSignatureNeeded()" sounded like it might have been a match for the setting of "assertion" and "responseandassertion".

![screen shot 2018-04-02 at 8 39 06 pm](https://user-images.githubusercontent.com/37702082/38223694-27598588-36ba-11e8-8bc1-b92f6059f739.png)

**Comment by gabbydotCMS** [comment]
Slack conversation on April/04/2018

Nathan (Ethode) [11:24 AM]
Regarding the signature question, I think the main issue is that the conversion from old to new config is not a 1 for 1 process. The new config is different from the old. Not a problem, but we need help where things don't line up in the rewire. The pick one or both option is new to the new config.
The old config did not enforce that or have that selection.

Gabriela Gonzalez [11:30 AM]
Right .. If I'm not wrong, V3 enforces response signature and allows Assertion signature to be optional (default behavior is to validate both Response and Assertion signature)
what we need in V4 is: 1) default behavior (validate both Response and Assertion), 2) validate Response signature only, 3) validate Assertion signature only

**Comment by gabbydotCMS** [comment]
@Nathan-Ethode .. what happens when you find one site associated to more than one SAML Configuration? Avoiding that is something that we (dotCMS) need to handle in the UI, but I was wondering how you are handling that case. Do you apply the configuration of the firs result you get from the cached configuration file?

**Comment by gabbydotCMS** [comment]
I'll document better and add more items, but these are the basic test cases that we should cover:

- SP Issuer URL: Make sure that if service.provider.issuer is defined in the Override Properties, the value defined in the SAML Config file does not get overridden  
- SP Endpoint Hostname: Make sure that if assertion.customer.endpoint.url is defined in the Override Properties, the value defined in the SAML Config file does not get overridden 
- Validation Type: Specific test cases are defined in #77, but we also need to validate that want.assertions.signed, authn.requests.signed, verify.assertion.signature, verify.signature.profile and verify.signature.credentials are ignored
- Enable/Disable SAML Config
- Add/Remove Sites to/from SAML Config
- Multiple SAML Config associated to the same site
- No SAML Config associated to the same site

**Comment by nkeiter** [comment]
@gabbydotCMS Currently sites are stored in cache under two different keys; hostname and identifier. The value stored under those keys is the idpConfigId. So in the case of the hostname keyed cache, the one saved to cache second would overwrite the first. The same thing would happen in the identifier keyed cache. We are not doing anything special right now to avoid this. The end result is that each site could only have one idpConfig when fetched via cache. The one fetched would be the one saved more recently.

https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/Ethode-Baseline/src/com/dotcms/plugin/saml/v3/cache/SamlCacheImpl.java#L237-L259

https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/Ethode-Baseline/src/com/dotcms/plugin/saml/v3/cache/SamlCacheImpl.java#L224-L235

**Comment by Nathan-Ethode** [comment]
@gabbydotCMS Currently sites are stored in cache under two different keys; hostname and identifier. The value stored under those keys is the idpConfigId. So in the case of the hostname keyed cache, the one saved to cache second would overwrite the first. The same thing would happen in the identifier keyed cache. We are not doing anything special right now to avoid this. The end result is that each site could only have one idpConfig when fetched via cache. The one fetched would be the one saved more recently.

https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/Ethode-Baseline/src/com/dotcms/plugin/saml/v3/cache/SamlCacheImpl.java#L237-L259

https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/Ethode-Baseline/src/com/dotcms/plugin/saml/v3/cache/SamlCacheImpl.java#L224-L235

**Comment by Nathan-Ethode** [comment]
@gabbydotCMS Just to clarify my last comment, I'm talking about the sites map from the JSON config.

**Comment by gabbydotCMS** [comment]
@thstave .. Update on our conversation regarding default values.

The following default config value / constants are not needed anymore:

- keyentryid / no constant associated to it
- verify.assertion.signature / DOT_SAML_VERIFY_ASSERTION_SIGNATURE 
- want.assertions.signed / DOTCMS_SAML_WANT_ASSERTIONS_SIGNED

so:

- default config values can be removed from https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/ethode-sp-endpoint-acs-rework/ROOT/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/dotcms-saml-default.properties 

and 

- constants can be removed from https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/4.0-4.3.x/src/com/dotcms/plugin/saml/v3/DotSamlConstants.java

keyentryid can be removed, for we don't use Java keystores anymore.

verify.assertion.signature and want.assertions.signed are now set by a mandatory field in the add/edit SAML Configuration dialog (Validation Type drop down).
