### ISSUE TITLE
REQ#1 - SP Metadata - AssertionConsumerService's Location should be the Login Endpoint

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#95]
When generating the SP Metadata, the Login Endpoint ($SPEndpointHostname/dotsaml/login/$SAML_Config_UUID) should be used as the location for the AssertionConsumerService. The value currently being assigned to this location seems to be the SP Endpoint Hostname instead.

**Comment by gabbydotCMS** [comment]
Hi @Fusty .. this is something we need you guys to change as soon as you are done with https://github.com/dotCMS/plugin-com.dotcms.dotsaml/issues/93

**Comment by thstave** [comment]
Reworked how SP Endpoint Hostname was being treated.  It was being used as the ACS.  Now the ACS is built from the SP Endpoint Hostname as in ($SPEndpointHostname/dotsaml/login/$SAML_Config_UUID) .  The change was committed under the ethode-sp-endpoint-acs-rework branch.

**Comment by gabbydotCMS** [comment]
Tested on code from ethode-sp-endpoint-acs-rework branch.
