### ISSUE TITLE
SP Endponint Hostname is still incorrect (both property name and usage)

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#97]

**Comment by chrismccracken** [comment]
UI display name for property "SP Endpoint Hostname" is incorrect:

![image](https://user-images.githubusercontent.com/3977301/40737913-ef4130be-63f6-11e8-9a19-7eef670984a8.png)

**Comment by chrismccracken** [comment]
Additionally, this property is used incorrectly in generating the SP metadata. A correct value for the property for this example should be just the hostname, and the scheme (https://) should prefix the hostname automatically in the generated SP metadata URLs for `SingleLogoutService` and `AssertionConsumerService`. Basically, just use the hostname property as a hostname not a URL prefix.

**Comment by thstave** [comment]
Chris.  I separated the scheme and the hostname for the SP Endpoint Hostname and committed it in the ethode-sp-endpoint-acs-rework branch.  You can now just enter the hostname in SP Endpoint Hostname.  We will always prefix it with https:// when building the metadata.
