### ISSUE TITLE
Security Issue: AuthnRequestsSigned on SP Metadata should always be true

### ISSUE THREAD

**Issue by gabbydotCMS** [dotCMS/plugin-com.dotcms.dotsaml#99]
When generating the SP metadata file, AuthnRequestsSigned should always set to true.

The value of this property is not related to the "Validation Type" property which instead defines whether or not the SP should expect Response/Assertion from the IdP to be signed.

dotCMS (SP)'s AuthnRequestsSigned should always be true.

**Comment by thstave** [comment]
@gabbydotCMS Could you please provide an example of what you are seeing.  Below is the first couple lines of an SP metadata file I looked at.  Look at the SPSSODescriptor line.  Is this what you are looking for?

<md:EntityDescriptor xmlns:md="urn:oasis:names:tc:SAML:2.0:metadata" entityID="https://demo.dotcms.com">
<md:SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="true" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:assertion urn:oasis:names:tc:SAML:2.0:protocol">
<md:KeyDescriptor use="signing">
<ds:KeyInfo xmlns:ds="http://www.w3.org/2000/09/xmldsig#">
<ds:X509Data>

**Comment by gabbydotCMS** [comment]
Hi @thstave. If you override authn.requests.signed to false, you should see  AuthnRequestsSigned="false" in the SP metadata file. What we want is to avoid that from ever happen, so basically this is about ignoring that property and always set AuthnRequestsSigned="true" in our metadata file.

authn.requests.signed can be removed from https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/ethode-sp-endpoint-acs-rework/ROOT/dotserver/tomcat-8.0.18/webapps/ROOT/WEB-INF/classes/dotcms-saml-default.properties

DOTCMS_SAML_AUTHN_REQUESTS_SIGNED can be removed from https://github.com/dotCMS/plugin-com.dotcms.dotsaml/blob/4.0-4.3.x/src/com/dotcms/plugin/saml/v3/DotSamlConstants.java

any check in the code done over the value of DOTCMS_SAML_AUTHN_REQUESTS_SIGNED can be eliminated.
